/**
 * Maps Google Sheet header labels (case-insensitive) to Tool fields.
 * Add aliases here if your sheet uses different column names.
 */
export const SHEET_COLUMN_ALIASES: Record<string, keyof import("./types/tool").Tool> = {
  name: "name",
  "tool name": "name",
  title: "name",
  type: "type",
  "tool type": "type",
  category: "type",
  description: "description",
  summary: "description",
  owner: "owner",
  "tool owner": "owner",
  contact: "owner",
  team: "team",
  department: "team",
  dept: "team",
  departments: "departments",
  "target teams": "departments",
  audience: "departments",
  builder_view: "builder_view",
  "builder view": "builder_view",
  "builder link": "builder_view",
  link: "builder_view",
  url: "builder_view",
  "tool link": "builder_view",
  user_view: "user_view",
  "user view": "user_view",
  "user link": "user_view",
  doc_link: "doc_link",
  "doc link": "doc_link",
  documentation: "doc_link",
  "documentation link": "doc_link",
  "google doc": "doc_link",
  status: "status",
  tags: "tags",
  updated_at: "updated_at",
  "updated at": "updated_at",
  "last updated": "updated_at",
};
